### ISSUE TITLE
BUG: Error after clicking on menu "Cost Type"

### ISSUE THREAD

**Issue by Adventurousdonut** [mikygee/immobilier#1]
Im using the english interface as the german one isn't as important yet, it can be translated more etc once a few modul bugs have been fixed.

![grafik](https://user-images.githubusercontent.com/110562645/183460999-d19d4f85-d0ac-4ab6-9e02-55741565982c.png)

When trying to list/modify already existing Cost Types by pressing on the "Cost type" menu it spits out following error:

Dolibarr has detected a technical error.
This information can be useful for diagnostic purposes (you can set option $dolibarr_main_prod to '1' to hide sensitive information):
Date: 20220808180213
Dolibarr: 15.0.0 - https://www.dolibarr.org
Level of features: 0
PHP: 7.2.24-0ubuntu0.18.04.10
Server: Apache
OS: Linux demo-dolibarr-biz 5.4.41-1-pve #1 SMP PVE 5.4.41-1 (Fri, 15 May 2020 15:06:08 +0200) x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0

Requested URL: /custom/ultimateimmo/cost/immocost_type_list.php?idmenu=423&mainmenu=immoreceipts&leftmenu=
Referer: https://demo.dolibarr.biz/custom/ultimateimmo/cost/immocost_type_card.php?action=create&idmenu=424&mainmenu=immoreceipts&leftmenu=
Menu manager: eldy_menu.php

Modules/Applications: user, modulebuilder, bookmark, import, export, fckeditor, cashdesk, mailing, paypal, multicurrency, socialnetworks, ultimateimmo, fastsearch, workflow, propal, emailcollector, contrat, expedition, ficheinter, supplier_proposal, incoterm, tax, loan, prelevement, product, comptabilite, stock, productbatch, projet, notification, agenda, banque, barcode, commande, don, ecm, expensereport, facture, fournisseur, holiday, margin, opensurvey, resource, salaries, societe, stripe, ticket, variants, website, recruitment, knowledgemanagement, adherent, reception, service, categorie, bom, mrp
Database type manager: mysqli
Latest database access request error: SELECT t.rowid, t.ref, t.label, t.famille, t.date_creation, t.tms, t.fk_user_creat, t.fk_user_modif, t.status FROM llx_ultimateimmo_immocost_type as t WHERE 1 = 1 ORDER BY t.label ASC LIMIT 26
Return code for latest database access request error: DB_ERROR_NOSUCHFIELD
Information for latest database access request error: Unknown column 't.fk_user_creat' in 'field list'

**Comment by mikygee** [comment]
Yes, as a work around edit class/immocost_type.class.php
search for fk_user_creat and when it looks like a sql query add an e at the end "fk_user_create"
There should be 2 occurences.

**Comment by Adventurousdonut** [comment]
![grafik](https://user-images.githubusercontent.com/110562645/183466953-a1e57cbb-78e0-4d84-b903-3b4b7cb83bd2.png)
Seems like it worked 👍

**Comment by mikygee** [comment]
Work around ok, I close it.
The project leader will need to choose if the correct syntax is with or witout an e.
