### ISSUE TITLE
BUG: Visual: Missing boldness on Birthday when creating a new Owner

### ISSUE THREAD

**Issue by Adventurousdonut** [mikygee/immobilier#2]
![grafik](https://user-images.githubusercontent.com/110562645/183462612-0e1e6abc-9728-475e-985d-f1e9d185670d.png)
When creating a new Owner the field "Birthday" is mandatory, yet it isn't bold like the other mandatory fields.

**Comment by mikygee** [comment]
The owner's birthday should be removed.
I opened a bug for that a few days ago
https://github.com/Darkjeff/immobilier/issues/54#issue-1292778436
I will add that if they want to keep the birthday it should be in bold.

As a workaround enter the date of today.

I close this issue and we will follow there
https://github.com/Darkjeff/immobilier/issues/54#issue-1292778436
